version: 2.1

commands:
        build:
                steps:
                        - checkout
                        #- run: git clone https://github.com/dgc-rhul/frontier.git repo
                        - run: ./frontier-bld.sh core 2>&1 | tee build.log 
executors:
        docker-executor:
                docker:
                        - image: danokeeffe/frontier:firsttry 

jobs:
        build-with-docker:
                executor: docker-executor
                steps:
                        - build 
workflows:
        build-with-docker:
                jobs:
                        - build-with-docker
